/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param description 
 * @param financialAssets 
 */


data class Portfolio (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "financialAssets")
    val financialAssets: kotlin.collections.List<FinancialAssets>

)

