/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package br.com.ed3.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param ticket 
 * @param enterpriseName 
 */


data class FinancialAssets (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "ticket")
    val ticket: kotlin.String,

    @Json(name = "enterpriseName")
    val enterpriseName: kotlin.String

)

