/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package br.com.ed3.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param transactionType 
 * @param assetID 
 * @param numberAssets 
 * @param transactionValue 
 */


interface Transaction {

    @Json(name = "id")
    val id: java.util.UUID
    @Json(name = "transactionType")
    val transactionType: kotlin.String
    @Json(name = "assetID")
    val assetID: FinancialAssets
    @Json(name = "numberAssets")
    val numberAssets: kotlin.Int
    @Json(name = "transactionValue")
    val transactionValue: java.math.BigDecimal
}

