openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/GMCORDEIRO.inf/Investimentos/1.0.0
  - description: Local Host
    url: http://localhost:8080
info:
  description: API for investments in financial assets
  version: "1.0.0"
  title: Investments
  contact:
    email: gmcordeiro.inf@gmail.com
tags:
  - name: production
    description: Operations in production environments
  - name: developers
    description: Operations available to admin developers
paths:
  /portfolio:
    get:
      tags:
        - production
      summary: searches portfolio
      operationId: searchPortfolio
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: Portfolio ID
          description: pass a opcional ID for search
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Portfolio'
        '400':
          description: is not ok
    post:
      tags:
        - production
      summary: adds an portfolio itens
      operationId: addPortfolio
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Portfolio'
        description: Portfólio item to add
  /asset:
    get:
      tags:
        - production
      summary: searches financial assets
      operationId: searchAssets
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: Asset ID
          description: pass a opcional ID for search
          required: false
          schema:
            type: string
            format: uuid
        - in: query
          name: Asset Ticket
          description: pass a opcional ticket for search
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FinancialAssets'
        '400':
          description: is not ok
    post:
      tags:
        - production
      summary: adds an Transaction itens
      operationId: addAssets
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinancialAssets'
        description: Portfólio item to add
  /transaction:
    get:
      tags:
        - production
      summary: searches Transactions
      operationId: searchTransaction
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: Asset ID
          description: pass a opcional ID for search
          required: false
          schema:
            type: string
            format: uuid
        - in: query
          name: Transaction ID
          description: pass a opcional ticket for search
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: is not ok
    post:
      tags:
        - production
      summary: adds an financial assets itens
      operationId: addTransactions
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        description: Portfólio item to add
components:
  schemas:
    Portfolio:
      type: object
      required:
        - id
        - description
        - financialAssets
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        description:
          type: string
          example: Real estate asset portfolio
        financialAssets:
          type: array
          items:
            $ref: '#/components/schemas/FinancialAssets'
    FinancialAssets:
      type: object
      required:
        - id
        - ticket
        - enterpriseName
        - unitAssetValue
        - numberAssets
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        ticket:
          type: string
          example: 'ITSA4'
        enterpriseName:
          type: string
          example: Itaúsa
    Transaction:
      type: object
      required:
        - id
        - transactionType
        - assetID
        - numberAssets
        - transactionValue
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        transactionType:
          type: string
          example: buy
        assetID:
          $ref: '#/components/schemas/FinancialAssets/properties/id'
        numberAssets:
          type: integer
        transactionValue:
          type: number
      discriminator:
        propertyName: transactionType
        mapping:
          buy: Buy
          sale: Sale