/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package br.com.ed3.domain.portfolio

import com.squareup.moshi.Json
import java.util.*

/**
 * 
 *
 * @param id 
 * @param transactionType 
 * @param assetID 
 * @param numberAssets 
 * @param transactionValue 
 */


data class Transaction(

    @Json(name = "id")
    val id: java.util.UUID = UUID.randomUUID(),

    @Json(name = "transactionType")
    val transactionType: String,

    @Json(name = "assetID")
    val assetID: java.util.UUID,

    @Json(name = "numberAssets")
    val numberAssets: Int,

    @Json(name = "transactionValue")
    val transactionValue: Double,
)

