/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package br.com.ed3.domain.assets


import com.squareup.moshi.Json
import java.util.UUID

/**
 * 
 *
 * @param id 
 * @param ticket 
 * @param enterpriseName 
 */


data class FinancialAssets (

    @Json(name = "id")
    val id: java.util.UUID = UUID.randomUUID(),

    @Json(name = "ticket")
    val ticket: kotlin.String,

    @Json(name = "enterpriseName")
    val enterpriseName: kotlin.String,

    @Json(name = "unitAssetValue")
    val unitAssetValue: kotlin.Double,

    @Json(name = "numberAssets")
    val numberAssets: kotlin.Int

)

